getwd()
setwd("C:/_research/homeworks/hw001/ExData_Plotting1")
#download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile="data.zip", method="curl")
#unzip ("data.zip", exdir = "./")

raw_data <- read.table("./household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
col_names <-names(raw_data)
raw_data$Timestamp = strptime(paste(raw_data$Date, raw_data$Time), "%d/%m/%Y %H:%M:%S")
raw_data["Date"]=as.Date(raw_data$Date, format="%d/%m/%Y")
data = subset(raw_data, Date >= "2007-02-01" & Date <=" 2007-02-02")
#data$time = strptime(data$Time,  format=" %H:%M:%S")
head(data)
str(data)
head(raw_data$Timestamp)

data$Global_active_power = as.numeric(data$Global_active_power)  
data$Global_reactive_power = as.numeric(data$Global_reactive_power)  
data$Voltage = as.numeric(data$Voltage)  
data$Global_intensity = as.numeric(data$Global_intensity)  
data$Sub_metering_1 = as.numeric(data$Sub_metering_1)  
data$Sub_metering_2 = as.numeric(data$Sub_metering_2)  
data$Sub_metering_3 = as.numeric(data$Sub_metering_3)  

par(mfrow = c(1,1))
with(data, hist(Global_active_power, xlab="Global Active Power (kilowatts)", col="red", main="Global Active Power" ) )
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()
